<script lang="ts">
	import type {
		Authors,
		AuthorsOnBook,
		Book,
		BookCategories,
		BookCategoriesOnBooks,
		CustomFields
	} from '@prisma/client';

	export let data: {
		read: CustomFields[];
		books: (Book & {
			authors: (AuthorsOnBook & {
				author: Authors;
			})[];
			categories: (BookCategoriesOnBooks & {
				bookCategory: BookCategories;
			})[];
		})[];
	};
	const { read, books } = data;
	const categoryMap = new Map();
	books.forEach((book) => {
		book.categories.forEach((bookCat) => {
			categoryMap.set(bookCat.bookCategory.id, bookCat.bookCategory.category);
		});
	});
	const categories = Array.from(categoryMap, ([id, category]) => ({ id, category }));
	let filteredCategories: { id: number; category: string }[] = [];

	const intro = read.find((rd) => rd.name === 'recently-read-2022-intro');
	const currentRead = read.find((rd) => rd.name === 'currently-reading');

	let singleBook:
		| (Book & {
				authors: (AuthorsOnBook & {
					author: Authors;
				})[];
				categories: (BookCategoriesOnBooks & {
					bookCategory: BookCategories;
				})[];
		  })
		| undefined;

	let isTruncated: boolean = true;

	const lastItem = (arr: Array<any>, i: number) => i === arr.length - 1;

	const truncate = (desc: string) => `${desc.substring(0, 280)}...`;

	const filterBy = (catId: number) => {
		const newFilter = categories.filter((cat) => cat.id === catId);
		filteredCategories = [...filteredCategories, ...newFilter];
	};

	const bookIsInCategories = (
		book: Book & {
			authors: (AuthorsOnBook & {
				author: Authors;
			})[];
			categories: (BookCategoriesOnBooks & {
				bookCategory: BookCategories;
			})[];
		}
	) => {
		const bookCategories = book.categories.map((bookCategory) => bookCategory.bookCategory);
		let found = false;
		bookCategories.forEach((category) => {
			found = !!filteredCategories.find((cat) => cat.id === category.id);
		});
		return found;
	};

	const isFiltered = (catId: number, cats: { id: number; category: string }[]) => {
		return !!cats.find((cat) => cat.id === catId);
	};

	const displayBook = (id: number) => {
		isTruncated = true;
		singleBook = books.find((book) => book.id === id);
	};

	const setTruncated = () => {
		isTruncated = !isTruncated;
	};
</script>

<div class="mb-4">
	{@html currentRead?.valueRendered}
	{@html intro?.valueRendered}
</div>

<hr />

<div class="my-4">
	<p>
		Filter by Category*:
		{#each categories as category (category.id)}
			<button
				class={`m-1 ${isFiltered(category.id, filteredCategories) ? 'button-primary' : 'button'}`}
				type="button"
				on:click={() => filterBy(category.id)}>{category.category}</button
			>
		{/each}
		{#if filteredCategories.length > 0}
			<button
				class="m-1 button-alternative"
				type="button"
				on:click={() => {
					filteredCategories = [];
				}}>Clear</button
			>
		{/if}
	</p>
	<p class="text-sm">*Categories autogenerated by Google API</p>
</div>

{#if !singleBook}
	<div class="columns-3 gap-4 not-prose">
		{#each books as book (book.id)}
			{#if filteredCategories.length === 0}
				<div class="mb-4">
					<button class="inline-block w-full" on:click|preventDefault={() => displayBook(book.id)}>
						<img
							src={book.thumbnail || `https://via.placeholder.com/130x200.png?text=${book.title}`}
							alt={book.title}
							class="w-full"
						/>
					</button>
				</div>
			{/if}
			{#if filteredCategories.length > 0 && bookIsInCategories(book)}
				<div class="mb-4">
					<button class="inline-block w-full" on:click|preventDefault={() => displayBook(book.id)}>
						<img
							src={book.thumbnail || `https://via.placeholder.com/130x200.png?text=${book.title}`}
							alt={book.title}
							class="w-full"
						/>
					</button>
				</div>
			{/if}
		{/each}
	</div>
{/if}

{#if singleBook}
	<div class="mb-8">
		<button
			type="button"
			class="button-alternative"
			on:click={() => {
				singleBook = undefined;
			}}>← Back</button
		>
	</div>
	<div class="flex space-x-8">
		<div class="flex-initial">
			<img
				src={singleBook.thumbnail ||
					`https://via.placeholder.com/130x200.png?text=${singleBook.title}`}
				alt={singleBook.title}
				class="book-img"
			/>
		</div>
		<div class="flex-1">
			<h1>{singleBook.title}</h1>
			{#if singleBook.subtitle}<h2>{singleBook.subtitle}</h2>{/if}
			{#if singleBook.authors.length > 0}<h3 class="mb-2">
					By:
					{#each singleBook.authors as authors, ida}
						{authors.author.name}{#if !lastItem(singleBook.authors, ida)}, {/if}
					{/each}
				</h3>{/if}
			{#if singleBook.description}
				{#if isTruncated}
					<p>{truncate(singleBook.description)}</p>
					<button class="button" type="button" on:click={() => setTruncated()}>Read More</button>
				{/if}
				{#if !isTruncated}
					<p>{singleBook.description}</p>
				{/if}
			{/if}
		</div>
	</div>
{/if}

<div class="my-8">
	<p class="text-sm">
		Book data provided by <a
			href="https://developers.google.com/books"
			rel="noreferrer noopener"
			target="_blank">Google Books API</a
		>
	</p>
</div>

<style>
	.book-img {
		margin: 0;
	}
</style>
